# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'inmuebles' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for inmuebles
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  target 'inmuebles-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'inmueblesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'inmuebles-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for inmuebles-tvOS

  
end
